// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6KYdB368SnCcWMnDdaMT_rwTYXTmpzc',
    appId: '1:1003301528697:web:6eabc565f21264714ee0a8',
    messagingSenderId: '1003301528697',
    projectId: 'think-1cecb',
    authDomain: 'think-1cecb.firebaseapp.com',
    storageBucket: 'think-1cecb.appspot.com',
    measurementId: 'G-CKKW1T9RWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-AVJbgze8uKmznbmrijq39F_sPHJIZOw',
    appId: '1:1003301528697:android:f6013d810e7b951b4ee0a8',
    messagingSenderId: '1003301528697',
    projectId: 'think-1cecb',
    storageBucket: 'think-1cecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPBsjxtZ4gAicPAn58PmTtEmxC1ilgpE',
    appId: '1:1003301528697:ios:b4ba984832c22c254ee0a8',
    messagingSenderId: '1003301528697',
    projectId: 'think-1cecb',
    storageBucket: 'think-1cecb.appspot.com',
    iosBundleId: 'com.example.bloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASPBsjxtZ4gAicPAn58PmTtEmxC1ilgpE',
    appId: '1:1003301528697:ios:b4ba984832c22c254ee0a8',
    messagingSenderId: '1003301528697',
    projectId: 'think-1cecb',
    storageBucket: 'think-1cecb.appspot.com',
    iosBundleId: 'com.example.bloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy6KYdB368SnCcWMnDdaMT_rwTYXTmpzc',
    appId: '1:1003301528697:web:2f84028286d4d4e94ee0a8',
    messagingSenderId: '1003301528697',
    projectId: 'think-1cecb',
    authDomain: 'think-1cecb.firebaseapp.com',
    storageBucket: 'think-1cecb.appspot.com',
    measurementId: 'G-8072LDENEJ',
  );
}
